# Support WRN Fix IT by using the funding links below
# Developed and Maintained by Waren Gonzaga

issuehunt: WarenGonzaga/wrn-fix-it
custom: ['https://bmc.xyz/warengonzaga','https://paypal.me/warengonzagaofficial']
